//
//  Words.swift
//  ChartTest
//
//  Created by 冯奕琦 on 2018/2/26.
//  Copyright © 2018年 冯奕琦. All rights reserved.
//

import Foundation
import UIKit

//不同语言
struct DefaultWords {
  static var noDataForCollecitionView = "Do not have events"
  static var noDataForCommontEvent = "No available common event"
  static var noDataForTimeManagement = "No historical data"
  static var percentange = "Ratio"
  static var quantity = "Quantity"
  static var trend = "Trend"
  static var daysAgoa = " days later"
  static var daysAges = "days ages"
  static var spendHours = "Time spent"
  static var planList = "PlanList"
  static var delete = "Delete"
  static var done = "Done"
  static var clear = "Clear"
  static var next = "Next"
  static var timeErrorForInputNumber1 = "Please enter a number before the colon"
  static var timeErrorForInputNumber2 = "Please enter a number before the first colon"
  static var timeErrorForInputNumber3 = "Please enter a number after the first colon"
  static var timeErrorForInputNumber4 = "Please enter a number before the second colon"
  static var timeErrorForInputNumber5 = "Please enter a number after the second colon"
  static var timeErrorForFormat = "Please enter a time format"
  static var timeErrorForBeyondRange = "Beyond time range (hours must less than 24,minutes must less than 60)"
  static var timeErrorOrder = "End time is not allowed before the start time"
  static var timeErrorConflictWithLast1 = "Conflict with ended at "
  static var timeErrorConflictWithLast2 = " event "
  static var timeErrorConflictWithLast3 = ""
  static var timeErrorConflictWithNext1 = "Conflict with the start at "
  static var timeErrorConflictWithNext2 = " event "
  static var timeErrorConflictWithNext3 = ""
  static var addNewEventAbove = "Add event from above"
  static var addNewEventBelow = "Add event from below"
  static var mon = "MON"
  static var tue = "TUE"
  static var wed = "WED"
  static var thu = "THU"
  static var fri = "FRI"
  static var sat = "SAT"
  static var sun = "SUN"
  static var today = "Today"
  static var tomorrow = "Tomorrow"
  static var dayAfterTomorrow = ""
  static var month = "-"
  static var day = ""
  static var OK = "OK"
  static var total = "Total"
  static var last7days = "7days"
  static var last15days = "15days"
  static var last30days = "30days"
  static var last90days = "90days"
  static var yesterDay = "Day"
  static var lastWeek = "Week"
  static var lastMonth = "Month"
  static var totally = "Total"
  static var timeLabelPlaceholder = "Time"
  static var nameLabelPlaceholder = "Event's name"
  static var unwindButton = "Back"
  static var hours = "h"
  static var mins = "m"
  static var IAPActivate = "Activate"
  static var IAPCancel = "Cancel"
  static var IAPTitle = "Get the full functionality of the application"
  static var IAPHint = "Hint"
  static var IAPRestore = "Restore full functionality(activated)"
  static var IAPCompleteActive = "Activate success"
  static var IAPConnectingMessage = "Connecting App Store"
  static var IAPPrice = "$ 0.99"
  static var infoImageArray = [#imageLiteral(resourceName: "info1"),#imageLiteral(resourceName: "info2"),#imageLiteral(resourceName: "info3"),#imageLiteral(resourceName: "info4")]
  static var deleteAllOldDataString = "Clear all data"
  
  static func changeToChinese(){
    DefaultWords.noDataForCollecitionView = "无事件"
    DefaultWords.noDataForCommontEvent = "暂无常用事件"
    DefaultWords.noDataForTimeManagement = "无历史数据"
    DefaultWords.percentange = "比例"
    DefaultWords.quantity = "数量"
    DefaultWords.trend = "趋势"
    DefaultWords.daysAgoa = "天后"
    DefaultWords.daysAges = "天前"
    DefaultWords.spendHours = "花费的时间"
    DefaultWords.planList = "计划表"
    DefaultWords.delete = "删除"
    DefaultWords.done = "完成"
    DefaultWords.clear = "清空"
    DefaultWords.next = "下一个"
    DefaultWords.timeErrorForInputNumber1 = "请在冒号之前输入数字"
    DefaultWords.timeErrorForInputNumber2 = "请在第一个冒号之前输入数字"
    DefaultWords.timeErrorForInputNumber3 = "请在第一个冒号之后输入数字"
    DefaultWords.timeErrorForInputNumber4 = "请在第二个冒号之前输入数字"
    DefaultWords.timeErrorForInputNumber5 = "请在第二个冒号之后输入数字"
    DefaultWords.timeErrorForFormat = "请输入时间格式"
    DefaultWords.timeErrorForBeyondRange = "超出时间范围（小时必须小于24,分钟必须小于60）"
    DefaultWords.timeErrorOrder = "结束时间不允许在开始时间之前"
    DefaultWords.timeErrorConflictWithLast1 = "与"
    DefaultWords.timeErrorConflictWithLast2 = "结束的"
    DefaultWords.timeErrorConflictWithLast3 = "事件冲突"
    DefaultWords.timeErrorConflictWithNext1 = "与"
    DefaultWords.timeErrorConflictWithNext2 = "开始的"
    DefaultWords.timeErrorConflictWithNext3 = "事件冲突"
    DefaultWords.addNewEventAbove = "从上添加"
    DefaultWords.addNewEventBelow = "从下添加"
    DefaultWords.mon = "星期一"
    DefaultWords.tue = "星期二"
    DefaultWords.wed = "星期三"
    DefaultWords.thu = "星期四"
    DefaultWords.fri = "星期五"
    DefaultWords.sat = "星期六"
    DefaultWords.sun = "星期天"
    DefaultWords.today = "今天"
    DefaultWords.tomorrow = "明天"
    DefaultWords.dayAfterTomorrow = "后天"
    DefaultWords.month = "月"
    DefaultWords.day = "日"
    DefaultWords.OK = "好的"
    DefaultWords.total = "总计"
    DefaultWords.last7days = "7天"
    DefaultWords.last15days = "15天"
    DefaultWords.last30days = "30天"
    DefaultWords.last90days = "90天"
    DefaultWords.yesterDay = "昨天"
    DefaultWords.lastWeek = "上周"
    DefaultWords.lastMonth = "上月"
    DefaultWords.totally = "全部"
    DefaultWords.timeLabelPlaceholder = "时间"
    DefaultWords.nameLabelPlaceholder = "事件名"
    DefaultWords.unwindButton = "返回"
    DefaultWords.hours = "时"
    DefaultWords.mins = "分"
    DefaultWords.IAPActivate = "激活"
    DefaultWords.IAPCancel = "取消"
    DefaultWords.IAPTitle = "获取应用的完整功能"
    DefaultWords.IAPHint = "提示"
    DefaultWords.infoImageArray = [#imageLiteral(resourceName: "ChieseInfo1"),#imageLiteral(resourceName: "ChieseInfo2"),#imageLiteral(resourceName: "ChieseInfo3"),#imageLiteral(resourceName: "ChieseInfo4")]
    DefaultWords.deleteAllOldDataString = "清空所有数据"
    DefaultWords.IAPRestore = "恢复完整功能(已激活)"
    DefaultWords.IAPCompleteActive = "激活成功"
    DefaultWords.IAPConnectingMessage = "正在连接 App Store"
    DefaultWords.IAPPrice = "¥ 1.00"
  }
}
